services:
    Unlooped\GridBundle\Repository\FilterRepository:
        public: true
        autoconfigure: true
        autowire: true
    Unlooped\GridBundle\Service\GridService:
        public: true
        arguments:
          - '@request_stack'
          - '@knp_paginator'
          - '@form.factory'
          - '@doctrine.orm.entity_manager'
          - '@session.flash_bag'
          - '@twig'
          - '@router.default'
          - '@Unlooped\GridBundle\Column\Registry\ColumnRegistry'
          - '@Unlooped\GridBundle\Filter\Registry\FilterRegistry'
          -
          -

    Unlooped\GridBundle\Service\AutocompleteService:
        public: true
        arguments:
            - '@doctrine'

    Unlooped\GridBundle\Form\EntityType:
        public: true
        tags:
            - 'form.type'
        arguments:
            - '@doctrine'
            - '@property_accessor'
